{% set name = "nanoflann" %}
{% set version = "1.6.0" %}
{% set sha256 = "f889026fbcb241e1e9d71bab5dfb9cc35775bf18a6466a283e2cbcd60edb2705" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jlblancoc/nanoflann/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [(win and vc<14) or ppc64le]
  # The nanoflann library is header only, so we do not need
  # to export the compiler run-time libraries.
  # They are just needed during the build to perform some checks.
  ignore_run_exports:
    - libcxx
    - libgcc-ng
    - libstdcxx-ng
    - vc
    - vs2015_runtime

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host: []  # Empty host dependency section

test:
  commands:
    - if not exist %LIBRARY_INC%\nanoflann.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\nanoflann\nanoflannConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\nanoflann\nanoflannConfigVersion.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\nanoflann\nanoflannTargets.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\pkgconfig\nanoflann.pc (exit 1)  # [win]
    - test -f ${PREFIX}/include/nanoflann.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/nanoflann/nanoflannConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/nanoflann/nanoflannConfigVersion.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/nanoflann/nanoflannTargets.cmake  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/nanoflann.pc  # [unix]

about:
  home: https://github.com/jlblancoc/nanoflann
  license: BSD
  license_file: COPYING
  summary: A C++ header-only library for Nearest Neighbor (NN) search wih KD-trees
  description: |
    nanoflann is a C++ header-only library for building KD-Trees, mostly optimized
    for 2D or 3D point clouds. nanoflann does not require compiling or installing.
    You just need to #include <nanoflann.hpp> in your code.
  doc_url: http://jlblancoc.github.io/nanoflann/
  dev_url: https://github.com/jlblancoc/nanoflann

extra:
  recipe-maintainers:
    - tadeu
    - jlblancoc
