travis:
  secure:
    BINSTAR_TOKEN: jZulVdS+rXnuUPYzdHob0XurNyCmedVEIJcdDlrz6qQH+aZUXG18FPCscMUGD1lOyaRuk2sjKuUcQQlGC5oPouii8bAZQHOp9Uq/jVhGuo54wF4KPHlgiiccD/N0zTpcj7a9j41/vRm48pVVdvRMoCSsBE/M3I4jtLwSeYEt9P/tg0D3Di1YwnN/vYkdNJf7VxBxzBFTgdSP74bjC9tFi2ux1fkc/ZfAFrq9/i+5MkaGki6ecRcRh6UiTHskhy8Tv+PZqQ+1yvrsVnctPlHbe/avgQ2i4/7lgRJwWVE7UJF1f46ejrrPmNPefjFkb/EMxRKm3eAoPAQYKX/ofzJMqsKuGLddPu0uHnSJNRYL53twzl4s89fiG/L6BLrZpKWS0NCcMwC5f/hr6ZvgtDM3uaAIQuc5oTjsusq6Gf8FtY2SrVNQFswiPFEvNg05EYEf/qvoxsip2dCpHxKRCPRKTRBYqleCduPVs4hZfniFsmsXY/nH0vOKmmTbDBH+5VFvsdWNbYwqWrlHnyJtgHyRWp51hPi/0z5Qn2306j9ABRqnnDNqsO32mxKYeEO+2sWrCsV31ICIshfVHjgbJACSj41vSTcqUMVdab4nPemCzqD63eecqdNC8gjl8Br7s8R2QC+fxOYwc/tXeEYMXkSlKNMlBBJh9KWM1vpwaLG/Ghk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
