travis:
  secure:
    BINSTAR_TOKEN: ebfffs0V2O4K/slOuAFZFWz1Z7MYbT0po3PdiQ4NFIcp8AxlHU/zoOL1HZWCZ/Xi7sb46TaU5gRmSNLTy/t0fZuCc042BSAi1PbOfWdN5bXBihwurMn28QqEpKM/7A1a1BjUGt45Z4WLO5fuLqEfc8iC03HRFi9a+yU+Feb2EuUs62fr47iTICtIaPVBIE+QM1YrMdopLNZsgHWAnvX2Bk+uy1tCamj8DwyfzdT00RvI/BMexqJJr5udATJM92rCWiyBCq7cw+ae286Dx5o6F/vStRzSeDO/NtdghE7IxH/HNKL+z1QGh5SJ8M+1Q0kFSBfYjtjFE5yt5cE8xkhbWf6TMpyApgivKF3uFkWpUnUAdl48kJ0JQYyfJ7R6A/VrBhUEhXQ8tWrcyPD5gRhvFTSrhwcAVueVZVz6gwC/zmn93mjrJbNsvmxxiUgsG/txknSasU0o4XdILAGT68ZZdF1qLjQayJOJ2iKg/QZ12wwbdtEmZdChlx0mxVbEt++AsyM7ImRxuyxkugNbgEdRu9+9gKQH0PbO1K73Emxa25cv1TK3ZUSyvk7Bu+9rEJspEkdFzefGqxkTbAr6DXLmd2+KcV6Z7sTqY/lBGkDlvcrdVpwVjv1HpVn+nISEfDiYIOXo09O9hzu8l/rqd0j1wjKKZteGW1EQ7kdaOgXX+xw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
